server:
  port: 8388
  max-http-header-size: 1024
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/government
    username: root
    password: Zrx@200401009
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 10MB

mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



